# Generated by Django 3.0 on 2023-01-31 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=70)),
                ('Commune', models.CharField(max_length=70)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thème', models.CharField(choices=[('maths', 'maths'), ('sciences', 'sciences'), ('physique', 'physique'), ('arabe', 'arabe'), ('anglais', 'anglais')], max_length=50)),
                ('titre', models.CharField(max_length=100)),
                ('catégorie', models.CharField(choices=[('primaire', 'primaire'), ('college', 'college'), ('lycee', 'lycee')], max_length=10)),
                ('modalité', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], max_length=8)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('tarif', models.CharField(max_length=30)),
                ('publié', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Adresse')),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonceur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publié',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='images')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
